a = int(input("Enter the first number: "))
b = int(input("Enter the second number: "))
print("The sum of", a, "and", b, "is:", a + b)
print("The difference of", a, "and", b, "is:", a - b)
print("The product of", a, "and", b, "is:", a * b)
print("The quotient of", a, "and", b, "is:", a / b)